name: Test Debug

on:
  workflow_call:

jobs:
  lint:
    name: Testing debug variant
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Android Specific thing(java)
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      # Android Specific thing(gradle)
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Unit Testing
      - name: Execute Gradle Test Debug Unit Test
        run: ./gradlew testDebugUnitTest
